# tasks file for docker-install
---
- name: Actualizar la maquina
  apt: 
    update_cache: yes 
    upgrade: dist

- name: Instalar aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Instalar prerequisitos
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    update_cache: true

- name: Agregar clave GPG de los repositorios de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Agregar repositorio oficial de Docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: install docker
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Instalar pip3
  become: true
  apt:
    update_cache: yes
    state: latest
    name: python3-pip

- name: Instalar Docker SDK para Python
  pip:
    name: docker

- name: Desinstalar Python requests
  pip:
    name: requests
    state: absent

- name: Instalar Python requests 2.28.1
  pip:
    name: requests==2.28.1

- name: "Agregar {{ hostvars[inventory_hostname]['USER'] }} usuario al grupo docker"
  user:
    name: "{{ hostvars[inventory_hostname]['USER'] }}"
    groups: 
      - docker
    append: yes